library(tidyverse)
library(BiodiversityR)
library(CCP)


#Structure the data for ordination

relict_comm_bio_m3 <- relict_data_doc %>% 
  select(worm_gm3_diplo,worm_gm3_apor, arth_gm3_tipu,arth_gm3_scara,
         arth_gm3_elat,arth_gm3_carab,arth_gm3_arma,arth_gm3_lepi,
         arth_gm3_curc,arth_gm3_staph,arth_gm3_taban,arth_gm3_meloi,
         arth_gm3_form,arth_gm3_asil,arth_gm3_chrys,arth_gm3_heteroc,
         arth_gm3_lepi) %>% 
  mutate(Diplo=worm_gm3_diplo,
         Apor=worm_gm3_apor,
         Tipu=arth_gm3_tipu,
         Scar=arth_gm3_scara,
         Elat=arth_gm3_elat,
         Cara=arth_gm3_carab,
         Arma=arth_gm3_arma,
         Curc=arth_gm3_curc,
         Stap=arth_gm3_staph,
         Taba=arth_gm3_taban) %>% 
  select(-worm_gm3_diplo,-worm_gm3_apor, -arth_gm3_tipu,-arth_gm3_scara,
         -arth_gm3_elat,-arth_gm3_carab,-arth_gm3_arma,-arth_gm3_lepi,
         -arth_gm3_curc,-arth_gm3_staph,-arth_gm3_taban,-arth_gm3_meloi,
         -arth_gm3_form,-arth_gm3_asil,-arth_gm3_chrys,-arth_gm3_heteroc,-arth_gm3_lepi)


relict_comm_bio_m3[is.na(relict_comm_bio_m3)] <- 0



relict_all_env <- relict_data_doc %>%
  select(loc,soil_moist_mean,dtw_cm_mean,ld,root_g_mean,
         om_mean,cond_mean,celcius_mean,bulk_dens_mean,nh4_mean,
         clay_mean,graminoid,forb,dtw_cm_max,elevation_mean,top_nmean) %>%
  column_to_rownames("loc") %>% 
  mutate(N = top_nmean,
         SOM = om_mean,
         DTW = dtw_cm_mean,
         Bulk = bulk_dens_mean,
         Cond = cond_mean,
         Mois = soil_moist_mean,
         Clay = clay_mean,
         Litter = ld,
         NH4 = nh4_mean) %>%
  select(-soil_moist_mean,-dtw_cm_mean,-ld,-root_g_mean,
         -om_mean,cond_mean,-bulk_dens_mean,-nh4_mean,
         -clay_mean,-cond_mean,-graminoid,-forb,-celcius_mean,
         -dtw_cm_max,-elevation_mean,-top_nmean)




#CCA for invertebrate community biomass in native (relict) sites

ord <- cca(relict_comm_bio_m3 ~ ., data=relict_all_env,na=na.omit)

ord
anova.cca(ord)
anova.cca(ord, by="axis",permutations = 1000)
plot(ord)
summary(ord)
scores(ord)

library(vegan)
library(ggfortify)
library(ggrepel)



ordiplot(ord)
autoplot(ord)



#Get CCA scores
df_species  <- data.frame(summary(ord)$species[,1:2]) %>% 
  rownames_to_column() %>% 
  mutate(rowname=ifelse(rowname=="Arma","Isop",rowname)) %>% 
  column_to_rownames(var="rowname")# get the species CC1 and CC2 scores
df_environ  <- scores(ord, display = 'bp') #get the environment vars CC1 and CC2 scores
df_sites <- data.frame(summary(ord)$sites[,1:2])

df_sites %>% 
  left_join(sites_long1)

cca1_varex<-round(summary(ord)$cont$importance[2,1]*100,2) #Get percentage of variance explained by first axis
cca2_varex<-round(summary(ord)$cont$importance[2,2]*100,2) #Get percentage of variance explained by second axis

#Set a scaling variable to multiply the CCA values, in order to get a very similar plot to the the one generated by plot(cca_model). You can adjust it according to your data
scaling_factor <- 3

cca1_plot <- ggplot(df_species, 
                    aes(x=CCA1, y=CCA2)) + 
  #Draw lines on x = 0 and y = 0
  geom_hline(yintercept=0, 
             linetype="dashed") +
  geom_vline(xintercept=0, 
             linetype="dashed") +
  coord_fixed()+
  #Add species text
  geom_text_repel(data=df_species, 
                  aes(x=CCA1,#Score in CCA1 to add species text
                      y=CCA2,#Score in CCA2 to add species text
                      label=rownames(df_species),
                      hjust=0.5*(1-sign(CCA1)),#Set the text horizontal alignment according to its position in the CCA plot
                      vjust=0.5*(1-sign(CCA2))),#Set the text vertical alignment according to its position in the CCA plot
                  color = "black",
                  size=11)+
  #Add environmental vars arrows
  geom_segment(data=df_environ, 
               aes(x=0, #Starting coordinate in CCA1 = 0 
                   xend=CCA1*scaling_factor,#Ending coordinate in CCA1  
                   y=0, #Start in CCA2 = 0
                   yend=CCA2*scaling_factor), #Ending coordinate in CCA2 
               color="firebrick1", #set color
               arrow=arrow(length=unit(0.01,"npc")),#Set the size of the lines that form the tip of the arrow
               size=2)+
  #Add environmental vars text
  geom_text_repel(data=df_environ, 
                  aes(x=CCA1*scaling_factor, 
                      y=CCA2*scaling_factor,
                      label=rownames(df_environ),
                      hjust=0.7*(1-sign(CCA1)),#Add the text of each environmental var at the end of the arrow
                      vjust=0.7*(1-sign(CCA2))),#Add the text of each environmental var at the end of the arrow 
                  color="firebrick1",
                  size=9)+
  #Set bw theme
  theme_classic()+
  theme(axis.text.x=element_text(size=70),
        axis.text.y = element_text(size=70),
        axis.title.x=element_text(size=70),
        axis.title.y = element_text(size=70),
        text = element_text(size = 70))+
  #Set x and y axis titles
  labs(x=paste0("CCA1 (",cca1_varex," %)"),
       y=paste0("CCA2 (",cca2_varex," %)"))+
  xlim(-4,4)+
  ylim(-4,4)


cca1_plot

ggsave(cca1_plot, file="cca1_plot.jpg", dpi=600, width=20, height=15, units="in")


##############################################################

#Examining the sites in the CCA

plot1 <- ordiplot(ord, choices=c(1,2))

sites_long1 <- sites.long(plot1, env.data=relict_all_env) %>% 
  rownames_to_column() %>% 
  mutate(loc=rowname) %>% 
  select(-rowname) %>% 
  merge(relict_wetness)

head(sites_long1)


species_long <- species.long(plot1) %>% 
  mutate(labels=ifelse(labels=="worm_gm3_diplo","Diplo",labels),
         labels=ifelse(labels=="worm_gm3_apor","Apor",labels),
         labels=ifelse(labels=="arth_gm3_tipu","Tipu",labels),
         labels=ifelse(labels=="arth_gm3_scara","Scara",labels),
         labels=ifelse(labels=="arth_gm3_staph","Staph",labels),
         labels=ifelse(labels=="arth_gm3_curc","Curc",labels),
         labels=ifelse(labels=="arth_gm3_carab","Carab",labels),
         labels=ifelse(labels=="arth_gm3_elat","Elat",labels),
         labels=ifelse(labels=="arth_gm3_strat","Strat",labels),
         labels=ifelse(labels=="arth_gm3_doli","Doli",labels),
         labels=ifelse(labels=="arth_gm3_heteroc","Heteroc",labels),
         labels=ifelse(labels=="arth_gm3_arma","Isop",labels),
         labels=ifelse(labels=="arth_gm3_taban","Taban",labels),
         labels=ifelse(labels=="arth_gm3_lepi","Lepi",labels),
         labels=ifelse(labels=="arth_gm3_canth","Canth",labels),
         labels=ifelse(labels=="arth_gm3_meloi","Meloi",labels),
         labels=ifelse(labels=="arth_gm3_asil","Asil",labels),
         labels=ifelse(labels=="arth_gm3_form","Form",labels),
         labels=ifelse(labels=="arth_gm3_phalangida","Phal",labels),
         labels=ifelse(labels=="arth_gm3_meloi","Meloi",labels),
         labels=ifelse(labels=="arth_gm3_penta","Penta",labels),
         labels=ifelse(labels=="arth_gm3_chrys","Chrys",labels),
         labels=ifelse(labels=="arth_gm3_myri","Myri",labels))




axis_long <- axis.long(ord, choices=c(1, 2))

ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  xlab(axis_long[1, "label"]) +
  ylab(axis_long[2, "label"]) +  
  scale_x_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +    
  geom_point(data=sites_long1, 
             aes(x=axis1, y=axis2), 
             size=5) +
  geom_segment(data=species_long, 
               aes(x=0, y=0, xend=axis1*4, yend=axis2*4), 
               colour="red", size=0.7, arrow=arrow()) +
  geom_text_repel(data=species_long, 
                  aes(x=axis1*4, y=axis2*4, label=labels),
                  colour="red")



vectors_envfit <- envfit(plot1, env=relict_all_env)
vectors_long <- vectorfit.long(vectors_envfit) %>% 
  mutate(vector=ifelse(vector=="root_g_mean","Root mass",vector),
         vector=ifelse(vector=="soil_moist_mean","Soil Moisture",vector),
         vector=ifelse(vector=="spring_depth21_cm_mean","Spring DTW 21",vector),
         vector=ifelse(vector=="spring_depth22_cm_mean","Spring DTW 22",vector),
         vector=ifelse(vector=="dtw_cm_mean","DTW",vector),
         vector=ifelse(vector=="wwis","WWIS",vector),
         vector=ifelse(vector=="c","C",vector),
         vector=ifelse(vector=="fqi","FQI",vector),
         vector=ifelse(vector=="sdi","SDI",vector),
         vector=ifelse(vector=="nh4_mean","NH4",vector),
         vector=ifelse(vector=="p_forb","Forb",vector),
         vector=ifelse(vector=="ld","Litter",vector),
         vector=ifelse(vector=="bg","BG",vector),
         vector=ifelse(vector=="om_mean","OM",vector),
         vector=ifelse(vector=="cond_mean","Soil Cond",vector),
         vector=ifelse(vector=="p_shrub","Shrub Cover",vector),
         vector=ifelse(vector=="celcius_mean","Soil Temp",vector),
         vector=ifelse(vector=="ribbon_mm_mean","Soil Ribbon Length",vector),
         vector=ifelse(vector=="top_nmean","NH4",vector),
         vector=ifelse(vector=="hydro","Hydro",vector),
         vector=ifelse(vector=="p_graminoid","Graminoid",vector),
         vector=ifelse(vector=="silt_mean","Silt",vector),
         vector=ifelse(vector=="sand_mean","Sand",vector),
         vector=ifelse(vector=="clay_mean","Clay",vector),
         vector=ifelse(vector=="elevation_mean","Elevation",vector),
         vector=ifelse(vector=="wet_use","WU",vector),
         vector=ifelse(vector=="bulk_dens_mean","Bulk",vector),
         vector=ifelse(vector=="p_tree","Tree",vector),
         vector=ifelse(vector=="e","E",vector),
         vector=ifelse(vector=="n","N",vector),
         vector=ifelse(vector=="bci","BCI",vector),
         vector=ifelse(vector=="bcw","BCW",vector),
         vector=ifelse(vector=="Longitude","Lon",vector),
         vector=ifelse(vector=="flood_num","Flood",vector),
         vector=ifelse(vector=="gley","Gley",vector),
         vector=ifelse(vector=="redox","Redox",vector),
         vector=ifelse(vector=="invasive","Invasive",vector))



cca_sites <- ggplot() + 
  geom_vline(xintercept = c(0), color = "grey70", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey70", linetype = 2) +  
  xlab(axis_long[1, "label"]) +
  ylab(axis_long[2, "label"]) +  
  scale_x_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +    
  geom_point(data=sites_long1, 
             aes(x=axis1, y=axis2,color=wetness), 
             size=5) +
  scale_color_manual(labels=c("wet"="Wet","non"="Dry"),values=c("black", "grey50")) +
  stat_ellipse(data=sites_long1, 
               aes(x=axis1, y=axis2,color=wetness),lwd = 1.2)+
  # geom_point(data=sites_long1, 
  #            aes(x=axis1, y=axis2,colour=wis_categories, shape=wis_categories), 
  #            size=2)+
  geom_segment(data=vectors_long, 
               aes(x=0, y=0, xend=axis1*3.5, yend=axis2*3.5), 
               colour="black", size=2)+
  geom_text_repel(data=vectors_long,
                  size=10,
                  alpha=0.85,  
                  aes(x=axis1*4, 
                      y=axis2*4, 
                      label=vector, 
                      hjust=0.5*(1-sign(axis1)),
                      vjust=0.5*(1-sign(axis2))),
                  colour="black")+
  # geom_text_repel(data=sites_long1,size=5,alpha=0.85, 
  #                 aes(x=axis1, y=axis2, label=labels),
  #                 colour="red")+
  theme_classic()+
  theme(axis.text.x=element_text(size=30),
        axis.text.y = element_text(size=30),
        axis.title.x=element_text(size=30),
        axis.title.y = element_text(size=30),
        text = element_text(size = 40),
        legend.position = c(0.8,0.9),
        legend.key.width = unit(3,"cm"))+
  labs(color="")


cca_sites

ggsave(cca_sites, file="cca_sites.jpg", dpi=600, width=20, height=15, units="in")



